Adzuna

In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd
import time

from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

job_queries = ["Accountant", "Data Engineer", "Data Analyst"]

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
driver.set_page_load_timeout(60)

wait = WebDriverWait(driver, 20)

all_jobs = []

for job_query in job_queries:

    print(f"\n Searching for: {job_query}")

    search_query = job_query.replace(" ", "+")
    url = f"https://www.adzuna.com/search?q={search_query}"

    driver.get(url)

    wait.until(
        EC.presence_of_element_located((By.CSS_SELECTOR, "h2"))
    )

    time.sleep(3)

    cards = driver.find_elements(By.CSS_SELECTOR, "div")

    for card in cards:

        try:
            title_element = card.find_element(By.CSS_SELECTOR, "h2 a")
            title = title_element.text
            link = title_element.get_attribute("href")
        except:
            continue

        try:
            company = card.find_element(By.CLASS_NAME, "ui-company").text
        except:
            company = ""

        try:
            location = card.find_element(By.CLASS_NAME, "ui-location").text
        except:
            location = ""

        try:
            salary = card.find_element(By.CLASS_NAME, "ui-salary").text
        except:
            salary = ""

        all_jobs.append([
            job_query,   
            title,
            company,
            location,
            salary,
            link
        ])

driver.quit()

df = pd.DataFrame(all_jobs, columns=[
    "search_keyword",
    "title",
    "company",
    "location",
    "salary",
    "link"
])

print(df)

df.to_csv("all_jobs.csv", index=False)

print("\n Saved to all_jobs.csv")

 Searching for: Accountant

 Searching for: Data Engineer

 Searching for: Data Analyst
   search_keyword                                              title  \
0      Accountant                                         Accountant
1      Accountant                                         Accountant
2      Accountant                                         Accountant
3      Accountant                                         Accountant
4      Accountant  Accountant / Certified Public Accountant (CPA)...
..            ...                                                ...
61   Data Analyst                                       Data Analyst
62   Data Analyst                                       Data Analyst
63   Data Analyst                                       Data Analyst
64   Data Analyst                                       Data Analyst
65   Data Analyst                                       Data Analyst

                             company                        location  \
0   EXPRESS EMPLOYMENT PROFESSIONALS      TEXARKANA, ARKANSAS, 71854
1   EXPRESS EMPLOYMENT PROFESSIONALS      TEXARKANA, ARKANSAS, 71854
2   EXPRESS EMPLOYMENT PROFESSIONALS      TEXARKANA, ARKANSAS, 71854
3
4   EXPRESS EMPLOYMENT PROFESSIONALS              NASH, TEXAS, 75569
..                               ...                             ...
61
62               BOOZ ALLEN HAMILTON         HONOLULU, HAWAII, 96814
63
64                 JUDGE GROUP, INC.  FRANKLIN TOWNSHIP, NEW JERSEY,
65

                                           salary  \
0   ESTIMATED: $59,940 per year ?\nTOP MATCH\nNEW
1   ESTIMATED: $59,940 per year ?\nTOP MATCH\nNEW
2   ESTIMATED: $59,940 per year ?\nTOP MATCH\nNEW
3
4                   ESTIMATED: $51,676 per year ?
..                                            ...
61
62             ESTIMATED: $93,420 per year ?\nNEW
63
64                 ESTIMATED: $105,953 per year ?
65

                                                 link
0   https://www.adzuna.com/land/ad/5701861335?se=b...
1   https://www.adzuna.com/land/ad/5701861335?se=b...
2   https://www.adzuna.com/land/ad/5701861335?se=b...
3   https://www.adzuna.com/land/ad/5701861335?se=b...
4   https://www.adzuna.com/land/ad/5692718515?se=b...
..                                                ...
61  https://www.adzuna.com/land/ad/5681129847?se=i...
62  https://www.adzuna.com/land/ad/5702988537?se=i...
63  https://www.adzuna.com/land/ad/5702988537?se=i...
64  https://www.adzuna.com/land/ad/5680356199?se=i...
65  https://www.adzuna.com/land/ad/5680356199?se=i...

[66 rows x 6 columns]

 Saved to all_jobs.csv

In [2]:
df

,search_keyword,title,company,location,salary,link
0,Accountant,Accountant,EXPRESS EMPLOYMENT PROFESSIONALS,"TEXARKANA, ARKANSAS, 71854","ESTIMATED: $59,940 per year ?\nTOP MATCH\nNEW",https://www.adzuna.com/land/ad/5701861335?se=b...
1,Accountant,Accountant,EXPRESS EMPLOYMENT PROFESSIONALS,"TEXARKANA, ARKANSAS, 71854","ESTIMATED: $59,940 per year ?\nTOP MATCH\nNEW",https://www.adzuna.com/land/ad/5701861335?se=b...
2,Accountant,Accountant,EXPRESS EMPLOYMENT PROFESSIONALS,"TEXARKANA, ARKANSAS, 71854","ESTIMATED: $59,940 per year ?\nTOP MATCH\nNEW",https://www.adzuna.com/land/ad/5701861335?se=b...
3,Accountant,Accountant,,,,https://www.adzuna.com/land/ad/5701861335?se=b...
4,Accountant,Accountant / Certified Public Accountant (CPA)...,EXPRESS EMPLOYMENT PROFESSIONALS,"NASH, TEXAS, 75569","ESTIMATED: $51,676 per year ?",https://www.adzuna.com/land/ad/5692718515?se=b...
...,...,...,...,...,...,...
61,Data Analyst,Data Analyst,,,,https://www.adzuna.com/land/ad/5681129847?se=i...
62,Data Analyst,Data Analyst,BOOZ ALLEN HAMILTON,"HONOLULU, HAWAII, 96814","ESTIMATED: $93,420 per year ?\nNEW",https://www.adzuna.com/land/ad/5702988537?se=i...
63,Data Analyst,Data Analyst,,,,https://www.adzuna.com/land/ad/5702988537?se=i...
64,Data Analyst,Data Analyst,"JUDGE GROUP, INC.","FRANKLIN TOWNSHIP, NEW JERSEY,","ESTIMATED: $105,953 per year ?",https://www.adzuna.com/land/ad/5680356199?se=i...
65,Data Analyst,Data Analyst,,,,https://www.adzuna.com/land/ad/5680356199?se=i...

Bayt

In [5]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import pandas as pd
import time

keyword = "accountant"

driver = webdriver.Chrome()

driver.get(f"https://www.bayt.com/en/egypt/jobs/{keyword}-jobs/")

time.sleep(5)

def scrape_bayt():

    jobs = []

    job_cards = driver.find_elements(By.CSS_SELECTOR, "li[data-js-job]")

    print("Jobs found:", len(job_cards))

    for job in job_cards[:20]:

        try:
            title = job.find_element(By.CSS_SELECTOR, ".t-default, .t-large").text
        except:
            title = "N/A"

        try:
            company = job.find_element(By.CSS_SELECTOR, ".t-bold").text
        except:
            company = "N/A"

        try:
            location = job.find_elements(By.CLASS_NAME, "t-mute")[1].text
        except:
            location = "N/A"

        try:
            link = job.find_element(By.TAG_NAME, "a").get_attribute("href")
        except:
            link = "N/A"

        try:
            salary = job.find_element(By.CSS_SELECTOR, ".jb-label-salary").text
        except:
            salary = "N/A"

        try:
            career = job.find_element(By.CSS_SELECTOR, ".jb-label-careerlevel").text
        except:
            career = "N/A"


        jobs.append({
            "Job Title": title,
            "Company": company,
            "Location": location,
            "Salary": salary,
            "Career Level": career,
            "Apply Link": link
        })

    return jobs


data = scrape_bayt()

df = pd.DataFrame(data)

print("\nJobs Found:", len(df))
print(df)

driver.quit()

Jobs found: 30

Jobs Found: 20
                                            Job Title  \
0                                  General Accountant
1                 Accountant (Suppliers & Petty Cash)
2                      Junior Accountant (outsourced)
3                                          Accountant
4                                  Accountant - Cairo
5                                  General Accountant
6                                  Accounting Manager
7            Accounts Receivable Accountant (Clients)
8    Assistant Manager - FP&A I Real Estate I Finance
9   Financial Analyst – Planning and Financial Ana...
10             Cost Accountant - Financial Accountant
11                                      Sr Accountant
12                                  Senior Accountant
13                       Junior Accountant (Odoo ERP)
14           Accounting Specialist - German + English
15                                    Site Accountant
16                                  Accountant - Odoo
17                                 General Accountant
18                                         Accountant
19  Accountant - Accounting to Reporting Shared Se...

                                      Company                      Location  \
0               امورتي لصناعة الملابس الجاهزة    Obour City · Cairo · Egypt
1                                    Summary:    Heliopolis · Cairo · Egypt
2                            Al Futtaim Group                 Cairo · Egypt
3                              مدارات الاغذية  Mandara · Alexandria · Egypt
4                                    Summary:                 Cairo · Egypt
5                        Qusah Trading Stores                 Cairo · Egypt
6                                   Mindspace                 Cairo · Egypt
7                                    Summary:    Heliopolis · Cairo · Egypt
8                            Al Futtaim Group                 Cairo · Egypt
9                                    Summary:    Heliopolis · Cairo · Egypt
10                                       Hvec     Abis · Alexandria · Egypt
11                                   RATP Dev                         Cairo
12                           SSC HR Solutions                         Cairo
13                    DeepSource Technologies                         Cairo
14                                Flairs Tech                         Cairo
15  Tawzef for Recruitment and HR Consultancy                         Cairo
16                               Franco Pinto                         Cairo
17                                    On-Hire                         Egypt
18                                   Dsquares                         Egypt
19                                Atlas Copco                         Cairo

                Salary                           Career Level  \
0      $1,000 - $1,500  Mid career · 1-10 Years of Experience
1                  N/A                             Mid career
2                  N/A                                    N/A
3                  N/A   Mid career · 2-4 Years of Experience
4                  N/A   Mid career · 3-5 Years of Experience
5                  N/A                                    N/A
6                  N/A                             Mid career
7                  N/A                             Mid career
8                  N/A                                    N/A
9                  N/A                             Mid career
10  EGP 0 - EGP 25,000   Mid career · 5-9 Years of Experience
11                 N/A                                    N/A
12                 N/A                                    N/A
13                 N/A                                    N/A
14                 N/A                                    N/A
15                 N/A                                    N/A
16                 N/A                                    N/A
17                 N/A                                    N/A
18                 N/A                                    N/A
19                 N/A                                    N/A

                                           Apply Link
0   https://www.bayt.com/en/egypt/jobs/%D9%85%D8%A...
1   https://www.bayt.com/en/egypt/jobs/accountant-...
2   https://www.bayt.com/en/egypt/jobs/junior-acco...
3   https://www.bayt.com/en/egypt/jobs/%D9%85%D8%A...
4   https://www.bayt.com/en/egypt/jobs/%D9%85%D8%A...
5   https://www.bayt.com/en/egypt/jobs/general-acc...
6   https://www.bayt.com/en/egypt/jobs/accounting-...
7   https://www.bayt.com/en/egypt/jobs/accounts-re...
8   https://www.bayt.com/en/egypt/jobs/assistant-m...
9   https://www.bayt.com/en/egypt/jobs/%D9%85%D8%B...
10  https://www.bayt.com/en/egypt/jobs/%D9%85%D8%A...
11  https://www.bayt.com/en/egypt/jobs/sr-accounta...
12  https://www.bayt.com/en/egypt/jobs/senior-acco...
13  https://www.bayt.com/en/egypt/jobs/junior-acco...
14  https://www.bayt.com/en/egypt/jobs/accounting-...
15  https://www.bayt.com/en/egypt/jobs/site-accoun...
16  https://www.bayt.com/en/egypt/jobs/accountant-...
17  https://www.bayt.com/en/egypt/jobs/general-acc...
18  https://www.bayt.com/en/egypt/jobs/accountant-...
19  https://www.bayt.com/en/egypt/jobs/accountant-...

In [6]:
df

,Job Title,Company,Location,Salary,Career Level,Apply Link
0,General Accountant,امورتي لصناعة الملابس الجاهزة,Obour City · Cairo · Egypt,"$1,000 - $1,500",Mid career · 1-10 Years of Experience,https://www.bayt.com/en/egypt/jobs/%D9%85%D8%A...
1,Accountant (Suppliers & Petty Cash),Summary:,Heliopolis · Cairo · Egypt,N/A,Mid career,https://www.bayt.com/en/egypt/jobs/accountant-...
2,Junior Accountant (outsourced),Al Futtaim Group,Cairo · Egypt,N/A,N/A,https://www.bayt.com/en/egypt/jobs/junior-acco...
3,Accountant,مدارات الاغذية,Mandara · Alexandria · Egypt,N/A,Mid career · 2-4 Years of Experience,https://www.bayt.com/en/egypt/jobs/%D9%85%D8%A...
4,Accountant - Cairo,Summary:,Cairo · Egypt,N/A,Mid career · 3-5 Years of Experience,https://www.bayt.com/en/egypt/jobs/%D9%85%D8%A...
5,General Accountant,Qusah Trading Stores,Cairo · Egypt,N/A,N/A,https://www.bayt.com/en/egypt/jobs/general-acc...
6,Accounting Manager,Mindspace,Cairo · Egypt,N/A,Mid career,https://www.bayt.com/en/egypt/jobs/accounting-...
7,Accounts Receivable Accountant (Clients),Summary:,Heliopolis · Cairo · Egypt,N/A,Mid career,https://www.bayt.com/en/egypt/jobs/accounts-re...
8,Assistant Manager - FP&A I Real Estate I Finance,Al Futtaim Group,Cairo · Egypt,N/A,N/A,https://www.bayt.com/en/egypt/jobs/assistant-m...
9,Financial Analyst – Planning and Financial Ana...,Summary:,Heliopolis · Cairo · Egypt,N/A,Mid career,https://www.bayt.com/en/egypt/jobs/%D9%85%D8%B...
10,Cost Accountant - Financial Accountant,Hvec,Abis · Alexandria · Egypt,"EGP 0 - EGP 25,000",Mid career · 5-9 Years of Experience,https://www.bayt.com/en/egypt/jobs/%D9%85%D8%A...
11,Sr Accountant,RATP Dev,Cairo,N/A,N/A,https://www.bayt.com/en/egypt/jobs/sr-accounta...
12,Senior Accountant,SSC HR Solutions,Cairo,N/A,N/A,https://www.bayt.com/en/egypt/jobs/senior-acco...
13,Junior Accountant (Odoo ERP),DeepSource Technologies,Cairo,N/A,N/A,https://www.bayt.com/en/egypt/jobs/junior-acco...
14,Accounting Specialist - German + English,Flairs Tech,Cairo,N/A,N/A,https://www.bayt.com/en/egypt/jobs/accounting-...
15,Site Accountant,Tawzef for Recruitment and HR Consultancy,Cairo,N/A,N/A,https://www.bayt.com/en/egypt/jobs/site-accoun...
16,Accountant - Odoo,Franco Pinto,Cairo,N/A,N/A,https://www.bayt.com/en/egypt/jobs/accountant-...
17,General Accountant,On-Hire,Egypt,N/A,N/A,https://www.bayt.com/en/egypt/jobs/general-acc...
18,Accountant,Dsquares,Egypt,N/A,N/A,https://www.bayt.com/en/egypt/jobs/accountant-...
19,Accountant - Accounting to Reporting Shared Se...,Atlas Copco,Cairo,N/A,N/A,https://www.bayt.com/en/egypt/jobs/accountant-...